server:
  port: 8765

spring:
  datasource:
    username: test_kitedge_aib
    password: RMneWj#K6H@q9EIqNLT*aBw1kg
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rds4231i4bf47j2pv069o.mysql.rds.aliyuncs.com:3306/test_kitedge_aib?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#    initialization-mode: always
    continue-on-error: true
    sql-script-encoding: utf-8
    schema:
    - classpath:sql/*.sql
    
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
    
  messages:
    basename: i18n/message
    encoding: utf-8

  redis:
    host: 47.103.93.159
    port: 6679
    password: AluPd$X27efx4lt


#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1 #链路追踪采样率，默认0.1

mybatis:
  #config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  - classpath:mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel : true
    useGeneratedKeys: true
  
mybatis-plus:
  mapper-locations: 
  - classpath:mapper/*Mapper.xml
  - classpath:mapper/**/*.xml
  type-aliases-package: com.kitedge.meeting.entity.domain
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


pagehelper: 
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true


feign:
  hystrix:
    enabled: true


#TIME OUT
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
          strategy: SEMAPHORE

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用

      
security:
  oauth2:
    resource:
      id: meeting
      user-info-uri: http://47.100.255.69:8081/api-auth/user
      prefer-token-info: false
      
  custom: #不需要oauth2验证的路径，每行最后的"\"确保字符串不会产生多余的空格
    noAuthUrls: ""