server:
  port: 8763

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_kitedge_aib?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库初始化
    # initialization-mode: always
    # continue-on-error: true
    # sql-script-encoding: utf-8
    # schema:
    #  - classpath:sql/start/start.sql
#    data:
#      - classpath:sql/first/data/*.sql

#设置上传文件的最值
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB


  redis:
    host: localhost
    port: 6379
    

  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
    
  messages:
    basename: i18n/message
    encoding: utf-8
    
  zipkin:
    base-url: http://localhost:8799
    enabled: true
  sleuth:
    sampler:
      probability: 1 #链路追踪采样率，默认0.1

  mail:
    host: smtp.mxhichina.com
    username: system@distrii.com
    password: Distrii520
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  mail:
#    host: smtp.163.com
#    username: 13163290613@163.com
#    password: luocan
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true


mybatis:
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  - classpath:mapper/**/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel : true
    useGeneratedKeys: true

mybatis-plus:
  mapper-locations: 
  - classpath:mapper/*Mapper.xml
  - classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.kitedge.user.entity.domain
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


feign:
  hystrix:
    enabled: false


#TIME OUT
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用

logging:
  level:
    com.kitedge: info

security:
  oauth2:
    resource:
      id: user
      user-info-uri: http://localhost:8888/user
      prefer-token-info: false

  custom: #不需要oauth2验证的路径，每行最后的"\"确保字符串不会产生多余的空格
    noAuthUrls: "/super/**\
    ,/bss/users/login\
    ,/bss/users/logout\
    ,/bss/users/refreshToken\
    ,/clients/customer/login\
    ,/clients/customer/logout\
    ,/hikvision/**\
    ,/**\
    "